from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

def create_synopsis():
    doc = Document()
    
    # Set default font to Times New Roman
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Times New Roman'
    font.size = Pt(12)

    # Title Page
    title = doc.add_heading('Project Synopsis: AI-Driven SOC Alert Prioritization System', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    p = doc.add_paragraph()
    p.add_run('Domain:').bold = True
    p.add_run(' Cyber Security & Machine Learning\n')
    p.add_run('Tools:').bold = True
    p.add_run(' Python, Scapy, FastAPI, XGBoost, React\n')
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_page_break()

    # Sections
    sections = [
        ("1. Abstract", "Modern Security Operations Centers (SOCs) are overwhelmed by 'alert fatigue'—the sheer volume of security alerts generated by traditional Intrusion Detection Systems (IDS). This project implements an intelligent SOC system that captures real-time network traffic, processes it into structured network flows, and uses advanced Machine Learning (ML) models (XGBoost and Random Forest) to classify and prioritize threats. The system aims to automate the triage process, allowing security analysts to focus on high-risk incidents, thereby reducing response time and operational overhead."),
        
        ("2. Introduction", "The increasing complexity of cyber-attacks requires rapid detection and response. Existing SOC tools often lack the context to distinguish between benign anomalies and critical threats. This project addresses this gap by:\n1. Automated Feature Extraction: Converting raw packet data into flows using Scapy.\n2. ML Integration: Using the CIC-IDS 2017 dataset for robust training.\n3. Real-Time Monitoring: Providing a live dashboard for traffic analysis and alert visualization.\n4. Priority Scoring: Assigning risk levels (Critical, High, Medium, Low) to each detected event."),
        
        ("3. Hardware & Software Requirements", "Hardware Requirements:\n- Processor: Intel Core i5 or higher (minimum 4 cores).\n- RAM: 8 GB DDR4 (16 GB recommended).\n- Storage: 50 GB available SSD space.\n- Network: Gigabit Ethernet Card (NIC).\n\nSoftware Requirements:\n- Operating System: Windows 10/11 or Ubuntu 20.04+.\n- Language: Python 3.10+.\n- Backend Framework: FastAPI.\n- ML Libraries: XGBoost, Scikit-learn, Pandas, NumPy.\n- Packet Capture: Scapy.\n- Frontend: React.\n- Server: Uvicorn."),
        
        ("4. Resources & Methodology", "Methodology:\nThe system follows a 4-stage pipeline:\n1. Data Acquisition: Capturing packets via Scapy.\n2. Flow Generation: Grouping packets by 5-tuple and extracting features like Flow Duration and Packet Lengths.\n3. Preprocessing & Classification: Scaling features and using XGBoost/RF for attack prediction.\n4. Priority Engine: Assigning risk scores and priority levels based on model output.\n\nAlgorithm Explanation:\n- XGBoost: A gradient-boosted decision tree library optimized for speed and performance on tabular data.\n- Random Forest: An ensemble learning method that uses multiple decision trees to improve stability and accuracy."),
        
        ("5. DFD and ER Diagrams", "Data Flow Diagram (Level 1):\nThe flow starts from the Network Traffic being sniffed by Scapy. The data is sent to the FastAPI backend where it is processed by the ML Model. Results are stored in the Alert Database and displayed on the Web Dashboard for the SOC Analyst.\n\nEntity Relationship (ER) Diagram:\n- ALERTS: Contains fields like alert_id, source_ip, dest_ip, attack_type, risk_score, and priority.\n- FLOWS: Contains flow_id, duration, and packet statistics.\n- MODELS: Tracks model_name, accuracy, and versions.\n- Relationships: One Flow originates one Alert; one Model classifies many Alerts."),
        
        ("6. Conclusion", "The Intelligent SOC system demonstrates the power of Machine Learning in cyber security. By automating alert triage and prioritization, it helps analysts focus on real threats, significantly enhancing the efficiency of security operations."),
        
        ("7. Future Enhancements", "- Anomaly Detection: Using unsupervised learning for Zero-day threats.\n- Automated Response: Integrating with Firewalls for proactive blocking.\n- Cloud Support: Monitoring hybrid cloud environments.\n- Model Retraining: Continuous learning from live feedback.")
    ]

    for heading, content in sections:
        doc.add_heading(heading, level=1)
        doc.add_paragraph(content)

    doc.save('d:/soc/reports/synopsis.docx')
    print("Synopsis created successfully at d:/soc/reports/synopsis.docx")

if __name__ == "__main__":
    create_synopsis()
